"""Added Avatar Column for Subreddits

Revision ID: 6fc5124cdbbd
Revises: 0806759e2957
Create Date: 2025-05-29 11:00:17.612043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc5124cdbbd'
down_revision = '0806759e2957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subreddits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subreddits', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
