"""Added Subreddit Wallpaper v0

Revision ID: 9d035bf223bd
Revises: 6fc5124cdbbd
Create Date: 2025-07-03 10:21:06.107281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d035bf223bd'
down_revision = '6fc5124cdbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subreddits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallpaper', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subreddits', schema=None) as batch_op:
        batch_op.drop_column('wallpaper')

    # ### end Alembic commands ###
